### ISSUE TITLE
Custom main resolution field in package.json other than "browser"?

### ISSUE THREAD

**Issue by yyx990803** [unpkg/npm-http-server#59]
Reading through the source, unpkg.com currently does respect the "browser" field for resolving the main file, but since Browserify uses the "browser" field for bundling, this leads to two problems:

1. Some packages use the object format of the "browser" field. This causes the resolution to use "main" instead and the default url (unkpg.com/package-name) is still unusable. Example: [superagent](https://unpkg.com/superagent).

2. In some cases I do want the resolved main to be different for **bundling** vs. **CDN usage**. For example I can preserve `process.env.NODE_ENV` in the for-bundle file, but have to hard code it in the CDN file. Right now for Vue I have to always use `https://unpkg.com/vue/dist/vue.js` instead of just `https://unpkg.com/vue`.

If there could an extra field, e.g. `"unpkg"`, that has the highest priority for specifying the default file to serve on unpkg.com, that would be great. This doesn't entirely solve (1) unless package authors add the extra field to their `package.json`, but for those who care they have an easier time controlling the file served for their package at the default url.

If you think this is reasonable, I'm happy to make a PR.

**Comment by mjackson** [comment]
Getting the defaults right is tricky ;)

In general I've tried to avoid adding any extra fields to `package.json` so we can integrate with the existing npm ecosystem as smoothly as possible. In the case of `superagent`, AFAICT they don't actually publish a UMD module to npm, so we can't help them until they do.

I guess the real problem here is that some people use `browser` to mean "this file is ready for the browser" (e.g. `d3` does this) while others use it to mean "use this file when you bundle for the browser". We serve the first group fine at the default URL, but not the second.

So ya, I'd be open to adding this feature. I can't really see a better alternative.

It should be as easy as adding another case [to this `if` statement](https://github.com/unpkg/npm-http-server/blob/561449c8622627402d4e1890cca8744d8ec0d22e/modules/index.js#L214-L220).

**Comment by mjackson** [comment]
Just FYI @yyx990803, I merged #61 and deployed this today. Thanks again for the suggestion and fix :)

**Comment by yyx990803** [comment]
Woot, thanks!
